dbfilename redis_queue.rdb
dir /home/dipdops_greno/csc/config/pids
pidfile /home/dipdops_greno/csc/config/pids/redis_queue.pid
bind 127.0.0.1
port 11006

aclfile /home/dipdops_greno/csc/config/redis_queue.acl
